name: Web CI

on:
  push:
    paths: src/**
  pull_request:
    paths: src/**

jobs:
  WebCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm cit
